horizon: 3000
tau: 0.1
dt: 0.1

# path of the pre-built map
map_path: "carla_map.png"


QP:
  alpha_fov : 1

Planner:
  # True if SST planner should be used for CBF control reference else False
  use_planner: False
  planner_max_time : 1.0
  mpt_model_path: "pursuer/planner/models/final_models/point_robot"
  mpt_enable: True
  base_planner: RRT

# bounds on angular velocity in rad/s
omega_lb: -1.0
omega_ub: 1.0
v_lb: -0
v_ub: 60

FoV:
  radius: 100
  psi: 1.0472
  kappa: 0.4

epsilon_s: 0.2
render: True
